SET UUID_COLLATION UNSIGNED;
SET COLLATION CHARSET_UTF8 STRENGTH PRIMARY;
CREATE USER IF NOT EXISTS "READER" SALT '3958f3bc2ead4f07' HASH '996ede105fb7386485a377c355e2a0c00b12a0ad6184d5dd86946812d11fbe54';
CREATE USER IF NOT EXISTS "SA" SALT '590d588ebd34b7b1' HASH '74577f57ba21fee9e0adeb310686933b2f4b3ceeb65d2f5fed026b7680c46525' ADMIN;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_36C4B8D6_8F09_4791_A643_FE5FF0409790" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_AD9CF959_2F56_4F5B_81D1_889E8A40B2F5" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_E90A2138_11B3_49A2_984C_B187D6522962" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_6D1003F7_5F27_4F47_8346_E7648D7D93AF" START WITH 1 BELONGS_TO_TABLE;
CREATE CACHED TABLE "PUBLIC"."USER"(
    "UID" UUID NOT NULL,
    "USERNAME" VARCHAR(64)
);
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("UID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER;
CREATE INDEX "PUBLIC"."USER_IDX_0" ON "PUBLIC"."USER"("UID");
CREATE INDEX "PUBLIC"."NAMEINDEX" ON "PUBLIC"."USER"("USERNAME");
CREATE CACHED TABLE "PUBLIC"."SONG"(
    "SID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_AD9CF959_2F56_4F5B_81D1_889E8A40B2F5" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_AD9CF959_2F56_4F5B_81D1_889E8A40B2F5",
    "UIDOWNER" UUID NOT NULL,
    "SONGTITLE" VARCHAR(128),
    "DURATION" INT DEFAULT 0
);
ALTER TABLE "PUBLIC"."SONG" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_26" PRIMARY KEY("SID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SONG;
CREATE INDEX "PUBLIC"."SONG_IDX_0" ON "PUBLIC"."SONG"("SID");
CREATE INDEX "PUBLIC"."UIDOWNERINDEX" ON "PUBLIC"."SONG"("UIDOWNER");
CREATE INDEX "PUBLIC"."SONGTITLEINDEX" ON "PUBLIC"."SONG"("SONGTITLE");
CREATE CACHED TABLE "PUBLIC"."PLAYLIST"(
    "PID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_6D1003F7_5F27_4F47_8346_E7648D7D93AF" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_6D1003F7_5F27_4F47_8346_E7648D7D93AF",
    "UIDOWNER" UUID,
    "PLAYLISTNAME" CLOB
);
ALTER TABLE "PUBLIC"."PLAYLIST" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("PID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PLAYLIST;
CREATE INDEX "PUBLIC"."PLAYLIST_IDX_0" ON "PUBLIC"."PLAYLIST"("PID");
CREATE CACHED TABLE "PUBLIC"."TAG"(
    "TID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_E90A2138_11B3_49A2_984C_B187D6522962" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_E90A2138_11B3_49A2_984C_B187D6522962",
    "UIDOWNER" UUID,
    "PID1" BIGINT,
    "PID2" BIGINT,
    "PID3" BIGINT,
    "TAGNAME" VARCHAR(128),
    "TAGTITLE" CLOB
);
ALTER TABLE "PUBLIC"."TAG" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("TID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TAG;
CREATE INDEX "PUBLIC"."TAG_IDX_0" ON "PUBLIC"."TAG"("TID");
CREATE INDEX "PUBLIC"."PID1INDEX" ON "PUBLIC"."TAG"("PID1");
CREATE INDEX "PUBLIC"."PID2INDEX" ON "PUBLIC"."TAG"("PID2");
CREATE INDEX "PUBLIC"."PID3INDEX" ON "PUBLIC"."TAG"("PID3");
CREATE INDEX "PUBLIC"."TAGNAMEINDEX" ON "PUBLIC"."TAG"("TAGNAME");
CREATE CACHED TABLE "PUBLIC"."PLAYLISTENTRY"(
    "EID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_36C4B8D6_8F09_4791_A643_FE5FF0409790" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_36C4B8D6_8F09_4791_A643_FE5FF0409790",
    "PID" BIGINT NOT NULL,
    "SID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."PLAYLISTENTRY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("EID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PLAYLISTENTRY;
CREATE INDEX "PUBLIC"."PLAYLISTENTRY_IDX_0" ON "PUBLIC"."PLAYLISTENTRY"("EID");
CREATE INDEX "PUBLIC"."PIDINDEX" ON "PUBLIC"."PLAYLISTENTRY"("PID");
CREATE INDEX "PUBLIC"."SIDINDEX" ON "PUBLIC"."PLAYLISTENTRY"("SID");
ALTER TABLE "PUBLIC"."PLAYLISTENTRY" ADD CONSTRAINT "PUBLIC"."PLAYLISTENTRY_FKEY_0" FOREIGN KEY("PID") REFERENCES "PUBLIC"."PLAYLIST"("PID") ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;
ALTER TABLE "PUBLIC"."SONG" ADD CONSTRAINT "PUBLIC"."SONG_FKEY_0" FOREIGN KEY("UIDOWNER") REFERENCES "PUBLIC"."USER"("UID") ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;
ALTER TABLE "PUBLIC"."PLAYLIST" ADD CONSTRAINT "PUBLIC"."PLAYLIST_FKEY_0" FOREIGN KEY("UIDOWNER") REFERENCES "PUBLIC"."USER"("UID") ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;
ALTER TABLE "PUBLIC"."TAG" ADD CONSTRAINT "PUBLIC"."TAG_FKEY_0" FOREIGN KEY("UIDOWNER") REFERENCES "PUBLIC"."USER"("UID") ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;
GRANT SELECT ON "PUBLIC"."PLAYLIST" TO "PUBLIC";
GRANT SELECT ON "PUBLIC"."PLAYLISTENTRY" TO "PUBLIC";
GRANT SELECT ON "PUBLIC"."SONG" TO "PUBLIC";
GRANT SELECT ON "PUBLIC"."TAG" TO "PUBLIC";
GRANT "PUBLIC" TO "READER";
GRANT SELECT ON "PUBLIC"."USER" TO "PUBLIC";
CHECKPOINT SYNC;
SHUTDOWN;