SET UUID_COLLATION UNSIGNED;
SET COLLATION CHARSET_UTF8 STRENGTH PRIMARY;
CREATE USER IF NOT EXISTS "READER" SALT '5eb445e140d081e9' HASH '6e63a36f0aa8002b62fee9ad0fc6158add096cf05db8c9fc5b100583e948f823';
CREATE USER IF NOT EXISTS "SA" SALT '5c9c3f8671bf3e11' HASH 'c8c5cd2074fb93877a821d4a255ed8ef70f9343445706fb09aee0f9e8ec81cf1' ADMIN;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_0D9339BC_7768_4860_B0B3_8682E5DA204C" START WITH 9 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_F47BA0C3_4192_4643_B8B0_911052321CFA" START WITH 5 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_DAB9B1DD_671B_4A69_9B71_5E913E554CEC" START WITH 7 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_CA0F1094_6E34_4A52_94F7_9182C257706A" START WITH 9 BELONGS_TO_TABLE;
CREATE CACHED TABLE "PUBLIC"."USER"(
    "UID" UUID NOT NULL,
    "USERNAME" VARCHAR(64)
);
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("UID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USER;
CREATE INDEX "PUBLIC"."USER_IDX_0" ON "PUBLIC"."USER"("UID");
CREATE INDEX "PUBLIC"."NAMEINDEX" ON "PUBLIC"."USER"("USERNAME");
CREATE CACHED TABLE "PUBLIC"."SONG"(
    "SID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_0D9339BC_7768_4860_B0B3_8682E5DA204C" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_0D9339BC_7768_4860_B0B3_8682E5DA204C",
    "UIDOWNER" UUID NOT NULL,
    "SONGTITLE" VARCHAR(128),
    "DURATION" INT DEFAULT 0
);
ALTER TABLE "PUBLIC"."SONG" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_26" PRIMARY KEY("SID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SONG;
CREATE INDEX "PUBLIC"."SONG_IDX_0" ON "PUBLIC"."SONG"("SID");
CREATE INDEX "PUBLIC"."UIDOWNERINDEX" ON "PUBLIC"."SONG"("UIDOWNER");
CREATE INDEX "PUBLIC"."SONGTITLEINDEX" ON "PUBLIC"."SONG"("SONGTITLE");
CREATE CACHED TABLE "PUBLIC"."PLAYLIST"(
    "PID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_F47BA0C3_4192_4643_B8B0_911052321CFA" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_F47BA0C3_4192_4643_B8B0_911052321CFA",
    "UIDOWNER" UUID,
    "PLAYLISTNAME" CLOB
);
ALTER TABLE "PUBLIC"."PLAYLIST" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("PID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PLAYLIST;
CREATE INDEX "PUBLIC"."PLAYLIST_IDX_0" ON "PUBLIC"."PLAYLIST"("PID");
CREATE CACHED TABLE "PUBLIC"."TAG"(
    "TID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_DAB9B1DD_671B_4A69_9B71_5E913E554CEC" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_DAB9B1DD_671B_4A69_9B71_5E913E554CEC",
    "UIDOWNER" UUID,
    "PID1" BIGINT,
    "PID2" BIGINT,
    "PID3" BIGINT,
    "TAGNAME" VARCHAR(128),
    "TAGTITLE" CLOB
);
ALTER TABLE "PUBLIC"."TAG" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("TID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TAG;
CREATE INDEX "PUBLIC"."TAG_IDX_0" ON "PUBLIC"."TAG"("TID");
CREATE INDEX "PUBLIC"."PID1INDEX" ON "PUBLIC"."TAG"("PID1");
CREATE INDEX "PUBLIC"."PID2INDEX" ON "PUBLIC"."TAG"("PID2");
CREATE INDEX "PUBLIC"."PID3INDEX" ON "PUBLIC"."TAG"("PID3");
CREATE INDEX "PUBLIC"."TAGNAMEINDEX" ON "PUBLIC"."TAG"("TAGNAME");
CREATE CACHED TABLE "PUBLIC"."PLAYLISTENTRY"(
    "EID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_CA0F1094_6E34_4A52_94F7_9182C257706A" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_CA0F1094_6E34_4A52_94F7_9182C257706A",
    "PID" BIGINT NOT NULL,
    "SID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."PLAYLISTENTRY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("EID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PLAYLISTENTRY;
CREATE INDEX "PUBLIC"."PLAYLISTENTRY_IDX_0" ON "PUBLIC"."PLAYLISTENTRY"("EID");
CREATE INDEX "PUBLIC"."PIDINDEX" ON "PUBLIC"."PLAYLISTENTRY"("PID");
CREATE INDEX "PUBLIC"."SIDINDEX" ON "PUBLIC"."PLAYLISTENTRY"("SID");
ALTER TABLE "PUBLIC"."PLAYLISTENTRY" ADD CONSTRAINT "PUBLIC"."PLAYLISTENTRY_FKEY_0" FOREIGN KEY("PID") REFERENCES "PUBLIC"."PLAYLIST"("PID") ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;
ALTER TABLE "PUBLIC"."SONG" ADD CONSTRAINT "PUBLIC"."SONG_FKEY_0" FOREIGN KEY("UIDOWNER") REFERENCES "PUBLIC"."USER"("UID") ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;
ALTER TABLE "PUBLIC"."PLAYLIST" ADD CONSTRAINT "PUBLIC"."PLAYLIST_FKEY_0" FOREIGN KEY("UIDOWNER") REFERENCES "PUBLIC"."USER"("UID") ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;
ALTER TABLE "PUBLIC"."TAG" ADD CONSTRAINT "PUBLIC"."TAG_FKEY_0" FOREIGN KEY("UIDOWNER") REFERENCES "PUBLIC"."USER"("UID") ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;
GRANT SELECT ON "PUBLIC"."PLAYLIST" TO "PUBLIC";
GRANT SELECT ON "PUBLIC"."PLAYLISTENTRY" TO "PUBLIC";
GRANT SELECT ON "PUBLIC"."SONG" TO "PUBLIC";
GRANT SELECT ON "PUBLIC"."TAG" TO "PUBLIC";
GRANT "PUBLIC" TO "READER";
GRANT SELECT ON "PUBLIC"."USER" TO "PUBLIC";
INSERT INTO "PUBLIC"."USER" VALUES
('ffffffff-ffff-0fff-ffff-ffffffffffff', 'SYSTEM'),
('00000000-0000-0000-0000-000000000000', 'SERVER');
INSERT INTO "PUBLIC"."TAG" VALUES
(1, 'ffffffff-ffff-0fff-ffff-ffffffffffff', 0, 0, 0, '[NO TAG]', NULL),
(2, 'ffffffff-ffff-0fff-ffff-ffffffffffff', 0, 0, 0, '[NO MUSIC]', NULL);
CHECKPOINT SYNC;
SHUTDOWN;